Update issues2md.yml

diff --git a/.github/workflows/issues2md.yml b/.github/workflows/issues2md.yml
--- a/.github/workflows/issues2md.yml
+++ b/.github/workflows/issues2md.yml
@@ -11,15 +11,28 @@ on:
     - cron: "0 * * * *"
 jobs:
   build:
+    name: Backup github issues to markdown files
     runs-on: ubuntu-latest
     steps:
-    - name: Set env
+    - name: Set output path
       run: echo "GH2MD_OUTPUT_PATH=archive/github/issues/" >> $GITHUB_ENV
-    - uses: actions/checkout@master
+    - name: Check output path
+      run: |
+        if [ -z "$GH2MD_OUTPUT_PATH" ]; then
+          echo "error: output path is empty"
+          exit 1
+        fi
+        pattern='^[a-zA-Z0-9_/.+~-]+$'
+        if ! printf '%s' "$GH2MD_OUTPUT_PATH" | tr $'\n' ' ' | grep -q -E "$pattern"; then
+          echo "error: output path does not match the pattern $pattern"
+          exit 1
+        fi
+    - name: checkout
+      uses: actions/checkout@master
       with:
         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
-    - name: Backup github issues to markdown files
+    - name: Run gh2md
       run: |
         pip3 install --user --upgrade setuptools
         pip3 install --user gh2md
@@ -50,8 +63,8 @@ jobs:
           done
     - name: "cleanup: move .ghmd files to separate folder"
       run: |
-        mkdir -p $GH2MD_OUTPUT_PATHghmd/
-        mv -v $GH2MD_OUTPUT_PATH*.ghmd $GH2MD_OUTPUT_PATHghmd/
+        mkdir -p $GH2MD_OUTPUT_PATH/ghmd/
+        mv -v $GH2MD_OUTPUT_PATH*.ghmd $GH2MD_OUTPUT_PATH/ghmd/
     - name: Commit files
       run: |
         git add $GH2MD_OUTPUT_PATH
